### PR TITLE
http/api: execute is now throwing IOException

### LINKED ISSUE #32: http: handle IOException errors
It looks like that the current implementation is not handling IOException and is emitting such kind of errors.

### PR DESCRIPTION
**Pull request by mgenov**
The result of the HTTP operation is now throwing IOException when there
is a timeout or communication error.

Note that this change is making API changes, and client code have to be
change too.

Fixes #32

### CODE REVIEW

File: src/test/java/com/clouway/chita/HttpClientTest.java [hunk 1]
```diff
@@ -378,17 +384,20 @@ public void cacheReadingOfResponse() throws Exception {
...
-    HttpResponse response = httpClient.execute(post);
-
-    assertThat(response.code(), is(408));
-    assertThat(response.isTimedOut(), is(true));
+    HttpResponse response = null;
+    try {
+      response = httpClient.execute(post);
+      fail("IOException was not thrown when connection timeouts ? ");
+    } catch (IOException e) {
+      assertThat(response, is(nullValue()));
```
Comment (tsony-tsonev) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: Hmm we lose the status code and we wont be able to differentiate communication failures and timeouts, also we will have to check everywhere for response != null && response.isSuccessful().

Comment (mgenov) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: You can by checking the instance of the IOException. Why you need to differentiate it ? In both cases you are not having InputStream from which to read.

Comment (tsony-tsonev) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: For example when we check if stb devices are online or not, the ACS responses with 408 if the device is offline. Currently we are not handling it this way but I think that we should, because now we return that the devices are offline even when there is no connection to the ACS which some times confuses the support guys that devices are offline when they are actually online but the ACS i just not responding.

Comment (mgenov) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: If ACS server is responding with http status code 408, then, no IO exception will be thrown I suppose, cause there is response.

Comment (tsony-tsonev) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: Yes SocketTimeoutException is thrown which is not handled any more.

Comment (mgenov) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: Why you think that SocketTimeoutException  is 408 status code?

Comment (tsony-tsonev) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: SocketTimeoutException is thrown when the given read or accept time is exceeded isn't that a timeout.

Comment (mgenov) [inline src/test/java/com/clouway/chita/HttpClientTest.java]:
```
mgenov:chita(handle_errors) $ curl -v -X GET http://localhost:3030
* Rebuilt URL to: http://localhost:3030/
*   Trying ::1...
* connect to ::1 port 3030 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 3030 failed: Connection refused
*   Trying fe80::1...
* connect to fe80::1 port 3030 failed: Connection refused
* Failed to connect to localhost port 3030: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 3030: Connection refused
```


```
mgenov:chita(handle_errors) $ curl -v -X GET http://ip.appspot.com
* Rebuilt URL to: http://ip.appspot.com/
*   Trying 74.125.71.141...
* Connected to ip.appspot.com (74.125.71.141) port 80 (#0)
> GET / HTTP/1.1
> Host: ip.appspot.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain;
< Date: Fri, 02 Oct 2015 07:23:51 GMT
< Server: Google Frontend
< Content-Length: 14
< 
* Connection #0 to host ip.appspot.com left intact
85.217.129.120%                                      
```

Comment (mgenov) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: btw, as you know SocketTimeoutException is IOException, so something like is valid: 

```java 
  try {
    response = client.execute(request);
  } catch(ConnectionTimeoutException e) {
     // mark device as something
  } catch(IOException e) {
     // generic error has occurred and server is not responding 
  }
```

Comment (tsony-tsonev) [inline src/test/java/com/clouway/chita/HttpClientTest.java]: LGTM but I'm not fan of the try catch mechanism. We should add issue and carefully refactor the existing code.
